version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://api.yourdomain.com
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080"
    volumes:
      - db_data:/var/lib/db
    environment:
      - TURSO_API_KEY=${TURSO_API_KEY}

volumes:
  db_data: